routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

Route::get('/teste/pdf',function(){
    return view('teste');
});


Route::get('/home', 'HomeController@index')->name('home');
Route::get('datatable/home','HomeController@dataTableJson')->name('home.datatable');
Route::get('home/categoria','HomeController@getCategorias');
Route::get('home/unidade','HomeController@getUnidades');

/**************ROTAS FUNÇÃO*************/
Route::resource('/funcao', 'FuncaoController');
Route::get('datatable/funcao','FuncaoController@dataTableJson')->name('funcao.datatable');

/**************ROTAS USUÁRIOS*************/
Route::resource('/user', 'UserController');
Route::get('datatable/user','UserController@dataTableJson')->name('user.datatable');
Route::get('/user/perfil/{useCodigo}','UserController@perfil')->name('user.perfil');//visualizar o perfil
Route::post('user/editar','UserController@editarPerfil'); //editar
Route::post('user/uploadFoto','UserController@upload')->name('user.uploadFoto');

/**************ROTAS CATEGORIAS*************/
Route::resource('/categoria', 'CategoriaController');
Route::get('datatable/categoria','CategoriaController@dataTableJson')->name('categoria.datatable');

/**************ROTAS UNIDADES*************/
Route::resource('/unidade', 'UnidadeController');
Route::get('datatable/unidade','UnidadeController@dataTableJson')->name('unidade.datatable');
Route::get('unidade/cidade/{estCodigo}','UnidadeController@getCidades')->name('unidade.cidade');

/**************ROTAS FORNECEDORES*************/
Route::resource('/fornecedor', 'FornecedorController');
Route::get('datatable/fornecedor','FornecedorController@dataTableJson')->name('fornecedor.datatable');
Route::get('fornecedor/verMais/{forCodigo}','FornecedorController@verMais')->name('fornecedor.verMais');
Route::get('fornecedor/cidade/{estCodigo}','FornecedorController@getCidades')->name('fornecedor.cidade');

/**************ROTAS PATRIMONIOS*************/
Route::resource('/patrimonio', 'PatrimonioController');
Route::get('patrimonios/json/{catCodigo?}','PatrimonioController@getPatrimonios');//preencher da tabela
Route::get('patrimonios/pesquisar','PatrimonioController@pesquisa');//pesquisa instantanea
Route::get('patrimonios/export', 'PatrimonioController@export')->name('patrimonio.export');

/**************ROTAS ITENS DE PATRIMONIOS*************/
Route::get('patrimonio/itensPatrimonio/{patCodigo}','PatrimonioController@getItensPatrimonio')->name('patrimonio.itensPatrimonio');
Route::resource('/itensPatrimonio','ItensPatrimonioController');
Route::get('patrimonio/itensPatrimonio/{itpCodigo}/edit','ItensPatrimonioController@edit');//editar um item de patrimonio
Route::get('patrimonio/itensPatrimonio/json/{patCodigo}/{tipoS?}/{valor?}','ItensPatrimonioController@getJson');//preenchendo a tabela
Route::get('filtrarPor/{tipo}','ItensPatrimonioController@preencherFiltro');//preencher o filtro
Route::get('itensPatrimonio/nota_fiscal/{nofCodigo}','ItensPatrimonioController@getNF');//visualizar nota fiscal
Route::get('itensPatrimonios/pesquisar','ItensPatrimonioController@pesquisa');//pesquisa instântanea
Route::get('itensPatrimonio/barcode/{itpCodigo}','ItensPatrimonioController@gerarCodigoBarras');//gerar código de barras
Route::get('itensPatrimonios/pesquisar/notaFiscal','ItensPatrimonioController@pesquisaNF');
Route::get('itens_patrimonio/export/{patCodigo}', 'ItensPatrimonioController@export')->name('itens_patrimonio.export');


/**************ROTAS NOTA FISCAL*************/
Route::resource('/notaFiscal', 'NotaFiscalController');
Route::get('datatable/notaFiscal','NotaFiscalController@dataTableJson')->name('notaFiscal.datatable');
Route::get('visualizar/nota_fiscal/{nofCodifo}','NotaFiscalController@verNF');
Route::post('/notaFiscal/cadastrar','NotaFiscalController@cadastrarJS')->name('notaFiscal.cadastrar');

/**************ROTAS AUTORIZACAO*************/
Route::resource('/autorizacao', 'AutorizacaoController');
Route::get('datatable/autorizacao','AutorizacaoController@dataTableJson')->name('autorizacao.datatable');

/**************ROTAS RELATÓRIOS*************/
Route::resource('relatorios', 'RelatoriosController');

/**************ROTAS EMPRESTIMOS*************/
Route::resource('/emprestimo', 'EmprestimoController');
Route::get('/emprestimo/patrimonios/json/{uniCodigo?}/{status?}/{catCodigo?}/{patCodigo?}','EmprestimoController@getPatrimonios');// listar patrimonios que podem ser emprestados
Route::get('datatable/emprestimo/{empStatus?}/{empData?}','EmprestimoController@dataTableJson')->name('emprestimo.datatable'); // listando os emprestimos
Route::get('/emprestimo/item/adicionar/{itpCodigo}','EmprestimoController@adicionar');// buscando item que foi selecionado para ser emprestado
Route::get('/emprestimo/verMais/{empCodigo}','EmprestimoController@verMais');// ver todos os detalhes do emprestimo
Route::get('/emprestimo/editar/json/{empCodigo}','EmprestimoController@getItensEditar'); // buscar itens que foram emprestados durante o cadastro para edição
Route::get('/emprestimo/editar/item/{itpCodigo}','EmprestimoController@getItem');
Route::get('/emprestimo/listar/pesquisar','EmprestimoController@pesquisarListagem');
Route::get('/emprestimo/adicionar/leitor/{itpCodigoBarras}','EmprestimoController@getItemLeitor'); // buscar item no banco pelo código de barras lido pelo leitor

/**************ROTAS DEVOLUÇÕES*************/
Route::get('/emprestimo/devolucao/index/','DevolucaoController@index')->name('emprestimo.indexD');
Route::get('/emprestimo/devolucao/itens/','DevolucaoController@devolucao')->name('emprestimo.devolucao');
Route::get('/devolucao/itens/{empCodigo}','DevolucaoController@telaDevolver');
Route::get('/datatable/devolucao/{empCodigo}','DevolucaoController@dataTableJson')->name('devolucao.datatable');
Route::post('/devolucao/storeJson','DevolucaoController@storeJson');
Route::resource('devolver', 'DevolucaoController');

/**************ROTAS DEPRECIAÇÃO*************/
Route::resource('depreciacao', 'DepreciacaoController');


/**************ROTAS TRANSFERÊNCIA*************/
Route::resource('transferencia', 'TransferirController');
Route::get('/transferencia/itens/{patCodigo}', 'TransferirController@getItens');
Route::get('/transferencia/pesquisar/itens/{patCodigo?}', 'TransferirController@pesquisar');

app/Patrimonio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\ItensPatrimonio;

class Patrimonio extends Model
{
    protected $table = "patrimonio";

    protected $primaryKey = "patCodigo";

    protected $fillable = [
        'patNome', 'patFoto', 'patQuantidade','categoria_catCodigo','fornecedor_forCodigo','patValorCompra',
    ];

    public function categoria(){
        return $this->belongsTo('App\Categoria','categoria_catCodigo','catCodigo');
    }

    public function user(){
        return $this->belongsTo('App\Users','users_useCodigo','useCodigo');
    }

    public function itens_patrimonio(){
        return $this->hasMany('App\ItensPatrimonio','patrimonio_patCodigo','patCodigo');
    }

    public function fornecedor(){
        return $this->belongsTo('App\Fornecedor', 'fornecedor_forCodigo','forCodigo');
        
    }

    public function getItens($patCodigo)
    {
        $itens = ItensPatrimonio::where('patrimonio_patCodigo',$patCodigo)
                                ->where('itpStatus','<>','Inativo')
                                ->get();
        return $itens;
    }

    


    
}

app/Http/Controllers/PatrimonioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Patrimonio;
use App\Categoria;
use App\Fornecedor;
use App\Unidade;
use App\NotaFiscal;
use App\ItensPatrimonio;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Storage;
use App\Exports\PatrimoniosExport;
use Auth;
class PatrimonioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
	{
        $this->middleware('auth');
        $this->middleware('multiple');
    }
    
    public function index()
    { 
            return view('patrimonio.create',
            [
            'categorias'=>Categoria::orderBy('catNome')->get(),
            'fornecedores'=> Fornecedor::orderBy('forNome')->get(),
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('patrimonio.create',
            [
                'categorias'=>Categoria::all(),
                'fornecedores'=> Fornecedor::all(),
            ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $regras =[
            'patNome' =>'required',
            'patFoto'=>'image|mimes:jpeg,png,jpg|max:2048',
            'categoria_catCodigo'=>'required|integer|min:1',
            'fornecedor_forCodigo'=>'required|integer|min:1',
            'patValorCompra'=>'required',
            
        ];
        $mensagens =[
            'patNome.required'=> 'Nome é requisito obrigatório',
            'patFoto.image'=>'Foto deve ser uma imagem (jpeg,png,jpg)',
            'patFoto.mimes'=>'Foto deve ser uma imagem (jpeg,png,jpg)',
            'patFoto.max'=>'Foto excedeu o tamanho máximo aceitável',
            'categoria_catCodigo.required'=> 'Categoria é requisito obrigatório',
            'categoria_catCodigo.min'=> 'Selecione uma categoria válida',
            'fornecedor_forCodigo.required'=>'Fornecedor é requisito obrigatório',
            'fornecedor_forCodigo.min'=>'Selecione um fornecedor válido',
            'patValorCompra.required'=>'Valor de compra é requisito obrigatório',
        ];

        $request->validate($regras,$mensagens);
        

        $path;
        
       //tratamento da imagem
       if($request->patFoto != null){
            $path = $request->file('patFoto')->store('patrimonios','public');
            if ( !$path ){
                return redirect()
                            ->back()
                            ->withSuccess('Falha ao fazer upload');
            }
       }else{
           $path  = 'imagens/default-patrimonio.png';
       }

        $user = Auth::user();
        if($user != null){

            $patrimonio = new Patrimonio();
            $patrimonio->patNome = $request->patNome;
            $patrimonio->categoria_catCodigo = $request->categoria_catCodigo;
            $patrimonio->fornecedor_forCodigo = $request->fornecedor_forCodigo;
            $patrimonio->users_useCodigo = $user->useCodigo;
            $patrimonio->patQuantidade = 0;
            /*trocando vírgula por ponto*/
            $request->patValorCompra = str_replace(".","", $request->patValorCompra);
            $request->patValorCompra = str_replace(",",".", $request->patValorCompra); 
            /* transformando a string em número */
            $patrimonio->patValorCompra = (float)$request->patValorCompra;
            $patrimonio->patFoto = $path;
            $patrimonio->save();

            return redirect()->route('patrimonio.index');
            
            
        }else{
            return view('auth.login');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $patrimonio = Patrimonio::find($id);
        if($patrimonio != null){
            return response()->json(['patrimonio'=>$patrimonio]);
        }

        return response('Vazio');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $patrimonio = Patrimonio::find($id);
        if($patrimonio != null){

            return view('patrimonio.edit',
            [
                'patrimonio'=>$patrimonio,
                'categorias'=>Categoria::orderBy('catNome')->get(),
                'fornecedores'=> Fornecedor::orderBy('forNome')->get(),
                ]);                 
        }
        return redirect()->back();
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $patrimonio = Patrimonio::find($id);
        if($patrimonio != null){
            $regras =[
                'patNome' =>'required',
                'patFoto'=>'image|mimes:jpeg,png,jpg|max:2048',
                'categoria_catCodigo'=>'required|integer|min:1',
                'patValorCompra'=>'required',
                'fornecedor_forCodigo'=>'required|integer|min:1',
                
            ];
            $mensagens =[
                'patNome.required'=> 'Nome é requisito obrigatório',
                'patFoto.image'=>'Foto deve ser uma imagem (jpeg,png,jpg)',
                'patFoto.mimes'=>'Foto deve ser uma imagem (jpeg,png,jpg)',
                'patFoto.max'=>'Foto excedeu o tamanho máximo aceitável',
                'categoria_catCodigo.required'=> 'Categoria é requisito obrigatório',
                'categoria_catCodigo.min'=> 'Selecione uma categoria válida',
                'fornecedor_forCodigo.required'=>'Fornecedor é requisito obrigatório',
                'fornecedor_forCodigo.min'=>'Selecione um fornecedor válido',
                'patValorCompra.required'=>'Valor de compra é requisito obrigatório',
                
            ];

            $request->validate($regras,$mensagens);

            $path;
            //tratando a imagem
           if($request->file('patFoto') != null){
                //apagando a foto da pasta
                $arquivo = $patrimonio->patFoto;
                Storage::disk('public')->delete($arquivo);
                //salvando a nova foto
                $path = $request->file('patFoto')->store('patrimonios','public');
                if ( !$path ){
                    return redirect()
                                ->back()
                                ->withSuccess('Falha ao fazer upload');
                }
           }else if($request->tirar_foto != null){ // se a pessoa tirar a foto
                //apagando a foto da pasta
                $arquivo = $patrimonio->patFoto;
                Storage::disk('public')->delete($arquivo);
                $path = 'imagens/default-patrimonio.png';
           }else{
               $path = $patrimonio->patFoto;
           }

            $user = Auth::user();
            $patrimonio->patNome = $request->patNome;
            $patrimonio->categoria_catCodigo = $request->categoria_catCodigo;
            $patrimonio->fornecedor_forCodigo = $request->fornecedor_forCodigo;
            $patrimonio->users_useCodigo = $user->useCodigo;
            
            /*trocando vírgula por ponto*/
            $request->patValorCompra = str_replace(".","", $request->patValorCompra);
            $request->patValorCompra = str_replace(",",".", $request->patValorCompra); 

            /* transformando a string em número */
            $patrimonio->patValorCompra = (float)$request->patValorCompra;
            $patrimonio->patValorCompra = $request->patValorCompra;
            $patrimonio->patFoto = $path;
            $patrimonio->update();
            return redirect()->route('patrimonio.index');
                
        }
        return redirect()
                ->back()
                ->withSuccess('Não foi possível atualizar o cadastro, tente mais tarde!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $patrimonio = Patrimonio::find($id);
        if($patrimonio != null){
            if($patrimonio->patFoto != null){
                //apagando a foto da pasta
            $arquivo = $patrimonio->patFoto;
            Storage::disk('public')->delete($arquivo);
            }
            $patrimonio->delete();
            return response()->json('true');
        }
        return response()->json('false');
    }

    //pegando todos os patrimonios
    public function getPatrimonios($catCodigo = null){
        $patrimonios = Patrimonio::when($catCodigo, function ($query, $catCodigo) {
                return $query->where('categoria_catCodigo', $catCodigo);
        })->with('categoria','fornecedor')->orderBy('patNome')->paginate(10);
            
        return response()->json(['patrimonios'=>$patrimonios]);   
    }

    //pegando todos os itens de patrimonio do patrimonio escolhido
    public function getItensPatrimonio($patCodigo){
        $patrimonio = Patrimonio::find($patCodigo);   
        $unidades = Unidade::orderBy('uniNome')->get();
        $notasFiscais =NotaFiscal::orderBy('nofDescricao')->get();                             
        return view('itensPatrimonio.index',
            ['patCodigo'=>$patCodigo,
             'patrimonio'=> $patrimonio,
             'unidades'=>$unidades,
             'notasFiscais'=>$notasFiscais]);
    }

    //metodo para pesquisa instântanea
    public function pesquisa(Request $request){

resources/views/patrimonio/depreciacao.blade.php
@extends('layouts.master')
@section('title', '- Deprecição')
@section('depreciacaoAtivo','bg-danger')
@section('principal')
@parent

<!--Ajax-->
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!--Mascara-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>
<!-- Select2 -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="{{asset('css/select2.css')}}">

<h3 style="margin-left:10px;"><i class="fa fa-calculator" style="font-weight:600px;"></i> Depreciação dos Patrimônios </h3>

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li id="li_1" class="active" id="li_1"><a href="#tab_1" data-toggle="tab" aria-expanded="true">Depreciação </a></li>
    </ul>
    <div class="tab-content">
        <!--Aba 1-->
        <div class="tab-pane active" id="tab_1">
            <div class="container-fluid">
                <div class="row">
                    <form action="{{route('depreciacao.store')}}" method="POST">
                        @csrf
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="categoria">Categorias<span class="text-danger">*</span></label>
                                <select name="categoria" id="categoria" class="form-control" onchange="buscarInfo(this.value)">
                                    <option value="">Selecione</option>
                                    @foreach ($categorias as $cat)
                                        <option value="{{$cat->catCodigo}}">{{$cat->catNome}}</option>
                                    @endforeach
                                </select>
                                @if($errors->get('categoria'))
                                     @foreach($errors->get('categoria') as $error)
                                        <span class="text-danger">{{ $error }}</span><br>
                                    @endForeach
                                @endIf
                            </div>
                            <div class="form-group">
                                <label for="catVidaUtil">Vida útil<span class="text-danger">*</span></label>
                                <input type="number" name="catVidaUtil" id="catVidaUtil" class="form-control">
                                @if($errors->get('catVidaUtil'))
                                     @foreach($errors->get('catVidaUtil') as $error)
                                        <span class="text-danger">{{ $error }}</span><br>
                                    @endForeach
                                @endIf
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="depAno">Ano<span class="text-danger">*</span></label>
                                <input type="number" name="depAno" id="depAno" class="form-control">
                                @if($errors->get('depAno'))
                                     @foreach($errors->get('depAno') as $error)
                                        <span class="text-danger">{{ $error }}</span><br>
                                    @endForeach
                                @endIf
                                <div class="pull-right" style="margin-bottom:5px;">
                                    <span class="text-danger">*</span><span>Campos Obrigatórios</span>
                                </div><br>
                            </div>
                            <div class="pull-right">
                                <div class="form-group">
                                    <a href="{{route('depreciacao.index')}}" class="btn btn-sm btn-danger">Cancelar</a>
                                    <button type="submit" class="btn btn-sm btn-primary">Aplicar</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>   
        </div> 
        <!--Aba 1-->
    </div>
</div>
     <!-- SELECT2 -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
     <script type="text/javascript">
      var baseurl = window.location.protocol + '//' + window.location.host + '/';
         $("#categoria").select2();

         $(function(){
             var now = new Date();
             depAno.value = now.getFullYear();
         })

         function buscarInfo(catCodigo){
            $.ajax({
				type: 'GET',
				url: baseurl + 'depreciacao/'+catCodigo,
                headers: {
						'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				cache: false,
					error: function(response) {
						console.log("Erro:\n"+response);
					},
					success: function(resposta) {
                        if(resposta != 'Vazio'){
                            catVidaUtil.value = resposta.categoria.catVidaUtil;
                           
                        }else{
                            alert('Não é possível realizar a deprecicao,tente mais tarde!');
                        }
					}
            });
         }
     </script>
    <script type="text/javascript" src="{{ asset('/data/js/bootstrap-select.js') }}"></script>    
@endsection

resources/views/patrimonio/transferencia.blade.php
@extends('layouts.master') @section('title', '- Transferência')@section('patrimonioAtivo','bg-danger') @section('principal') @parent

<!--Ajax-->
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!--Mascara-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>
<!-- Estilo tabela -->
<link rel="stylesheet" href="{{asset('css/table.css')}}">
<!-- Select2 -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="{{asset('css/select2.css')}}">

<h3 style="margin-left:10px;"><i class="fa fa-share" aria-hidden="true"></i> Transferência de Patrimônios </h3>

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="active" id="li_1"><a href="#tab_1" data-toggle="tab" aria-expanded="true">Transferência</a></li>
    </ul>
    <div class="tab-content">
        <!--Aba 1-->
        <div class="tab-pane active " id="tab_1">
            <div class="box-body box-success">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-6">
                            <form action="{{route('transferencia.store')}}" id="formTrans" method="POST">
                                @csrf
                                <div class="form-group">
                                    <label for="unidade">Transferir para: <span class="text-danger">*</span></label></br>
                                    <select name="unidade" id="unidade" class="form-control">
                                        <option value="">Selecione</option>
                                        @foreach ($unidades as $uni)
                                            <option value="{{$uni->uniCodigo}}">{{$uni->uniNome}}</option>
                                        @endforeach
                                    </select>
                                    @if($errors->get('unidade'))
                                        @foreach($errors->get('unidade') as $error)
                                            <span class="text-danger">{{ $error }}</span><br>
                                        @endForeach
                                    @endIf
                                </div>
                                <div class="form-group">
                                    <label for="patrimonio">Selecione o patrimônio<span class="text-danger">*</span></label></br>
                                    <select name="patrimonio" id="patrimonio" class="form-control" onchange="carregarItens(1,this.value)">
                                        <option value="0">Selecione</option>
                                        @foreach ($patrimonios as $pat)
                                            <option value="{{$pat->patCodigo}}">{{$pat->patNome}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group" style="margin-bottom:0px;">
                                    <label for="itens-table">Selecione os itens que deseja transferir: <span class="text-danger">*</span></label>
                                    <input type="hidden" name="itensT[]" id="itensT"><br>
                                    @if($errors->get('itensT'))
                                        @foreach($errors->get('itensT') as $error)
                                            <span class="text-danger">{{ $error }}</span><br>
                                        @endForeach
                                    @endIf
                                </div>
                            </form>
                        </div>
                        <div class="col-lg-12">
                            <div class="row " style="float: right;">
                                <div class="col-12">
                                    <label for="pesquisa">Pesquisar</label>
                                    <input type="search" id="pesquisa" name="pesquisa">
                                </div>
                                <div class="col-12">
                                    <div class="checkbox">
                                        <label for="tr">
                                            <input type="checkbox" id="tr" name="tr" onclick="transferirTodos()">
                                            <span class="cr"><i class="cr-icon glyphicon glyphicon-ok"></i></span>
                                             Selecionar Todos
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                            
                        
                        <div class="col-lg-12" style="margin-top:5px;">
                            <div class="table-responsive">
                                <table class="table table-hover " id="itens-table">
                                    <thead>
                                        <tr>
                                            <th class="text-center">#</th>
                                            <th class="text-center">Código de Barras</th>
                                            <th class="text-center">Unidade</th>
                                            <th class="text-center">Status</th>
                                            <th class="text-center">Situação</th>
                                            <th class="text-center">Tipo</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="text-center"  colspan="6">Nenhum patrimônio selecionado</td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div> 
                                    <span id="card-title" style="display: none;"></span>
                                    <span class="pull-right">
                                        <nav id="pagination"  style="display: none;">
                                            <ul class="pagination">
                                            </ul>
                                        </nav>
                                    </span>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <br>
                            <div class="pull-right">
                                <div class="form-group">
                                    <a href="{{route('transferencia.index')}}" class="btn btn-sm btn-danger">Cancelar</a>
                                    <button type="button" onclick="submeter()" class="btn btn-sm btn-primary">Transferir</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>                      
            </div>  
        </div>
        <!--Aba 1--> 
    </div>
</div>
</br>
    <!-- SELECT2 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/transferencia.js') }}"></script>
    <script type="text/javascript" src="{{ asset('/data/js/bootstrap-select.js') }}"></script>    
@endsection