routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

Route::get('/teste/pdf',function(){
    return view('teste');
});


Route::get('/home', 'HomeController@index')->name('home');
Route::get('datatable/home','HomeController@dataTableJson')->name('home.datatable');
Route::get('home/categoria','HomeController@getCategorias');
Route::get('home/unidade','HomeController@getUnidades');

/**************ROTAS FUNÇÃO*************/
Route::resource('/funcao', 'FuncaoController');
Route::get('datatable/funcao','FuncaoController@dataTableJson')->name('funcao.datatable');

/**************ROTAS USUÁRIOS*************/
Route::resource('/user', 'UserController');
Route::get('datatable/user','UserController@dataTableJson')->name('user.datatable');
Route::get('/user/perfil/{useCodigo}','UserController@perfil')->name('user.perfil');//visualizar o perfil
Route::post('user/editar','UserController@editarPerfil'); //editar
Route::post('user/uploadFoto','UserController@upload')->name('user.uploadFoto');

/**************ROTAS CATEGORIAS*************/
Route::resource('/categoria', 'CategoriaController');
Route::get('datatable/categoria','CategoriaController@dataTableJson')->name('categoria.datatable');

/**************ROTAS UNIDADES*************/
Route::resource('/unidade', 'UnidadeController');
Route::get('datatable/unidade','UnidadeController@dataTableJson')->name('unidade.datatable');
Route::get('unidade/cidade/{estCodigo}','UnidadeController@getCidades')->name('unidade.cidade');

/**************ROTAS FORNECEDORES*************/
Route::resource('/fornecedor', 'FornecedorController');
Route::get('datatable/fornecedor','FornecedorController@dataTableJson')->name('fornecedor.datatable');
Route::get('fornecedor/verMais/{forCodigo}','FornecedorController@verMais')->name('fornecedor.verMais');
Route::get('fornecedor/cidade/{estCodigo}','FornecedorController@getCidades')->name('fornecedor.cidade');

/**************ROTAS PATRIMONIOS*************/
Route::resource('/patrimonio', 'PatrimonioController');
Route::get('patrimonios/json/{catCodigo?}','PatrimonioController@getPatrimonios');//preencher da tabela
Route::get('patrimonios/pesquisar','PatrimonioController@pesquisa');//pesquisa instantanea
Route::get('patrimonios/export', 'PatrimonioController@export')->name('patrimonio.export');

/**************ROTAS ITENS DE PATRIMONIOS*************/
Route::get('patrimonio/itensPatrimonio/{patCodigo}','PatrimonioController@getItensPatrimonio')->name('patrimonio.itensPatrimonio');
Route::resource('/itensPatrimonio','ItensPatrimonioController');
Route::get('patrimonio/itensPatrimonio/{itpCodigo}/edit','ItensPatrimonioController@edit');//editar um item de patrimonio
Route::get('patrimonio/itensPatrimonio/json/{patCodigo}/{tipoS?}/{valor?}','ItensPatrimonioController@getJson');//preenchendo a tabela
Route::get('filtrarPor/{tipo}','ItensPatrimonioController@preencherFiltro');//preencher o filtro
Route::get('itensPatrimonio/nota_fiscal/{nofCodigo}','ItensPatrimonioController@getNF');//visualizar nota fiscal
Route::get('itensPatrimonios/pesquisar','ItensPatrimonioController@pesquisa');//pesquisa instântanea
Route::get('itensPatrimonio/barcode/{itpCodigo}','ItensPatrimonioController@gerarCodigoBarras');//gerar código de barras
Route::get('itensPatrimonios/pesquisar/notaFiscal','ItensPatrimonioController@pesquisaNF');
Route::get('itens_patrimonio/export/{patCodigo}', 'ItensPatrimonioController@export')->name('itens_patrimonio.export');


/**************ROTAS NOTA FISCAL*************/
Route::resource('/notaFiscal', 'NotaFiscalController');
Route::get('datatable/notaFiscal','NotaFiscalController@dataTableJson')->name('notaFiscal.datatable');
Route::get('visualizar/nota_fiscal/{nofCodifo}','NotaFiscalController@verNF');
Route::post('/notaFiscal/cadastrar','NotaFiscalController@cadastrarJS')->name('notaFiscal.cadastrar');

/**************ROTAS AUTORIZACAO*************/
Route::resource('/autorizacao', 'AutorizacaoController');
Route::get('datatable/autorizacao','AutorizacaoController@dataTableJson')->name('autorizacao.datatable');

/**************ROTAS RELATÓRIOS*************/
Route::resource('relatorios', 'RelatoriosController');

/**************ROTAS EMPRESTIMOS*************/
Route::resource('/emprestimo', 'EmprestimoController');
Route::get('/emprestimo/patrimonios/json/{uniCodigo?}/{status?}/{catCodigo?}/{patCodigo?}','EmprestimoController@getPatrimonios');// listar patrimonios que podem ser emprestados
Route::get('datatable/emprestimo/{empStatus?}/{empData?}','EmprestimoController@dataTableJson')->name('emprestimo.datatable'); // listando os emprestimos
Route::get('/emprestimo/item/adicionar/{itpCodigo}','EmprestimoController@adicionar');// buscando item que foi selecionado para ser emprestado
Route::get('/emprestimo/verMais/{empCodigo}','EmprestimoController@verMais');// ver todos os detalhes do emprestimo
Route::get('/emprestimo/editar/json/{empCodigo}','EmprestimoController@getItensEditar'); // buscar itens que foram emprestados durante o cadastro para edição
Route::get('/emprestimo/editar/item/{itpCodigo}','EmprestimoController@getItem');
Route::get('/emprestimo/listar/pesquisar','EmprestimoController@pesquisarListagem');
Route::get('/emprestimo/adicionar/leitor/{itpCodigoBarras}','EmprestimoController@getItemLeitor'); // buscar item no banco pelo código de barras lido pelo leitor

/**************ROTAS DEVOLUÇÕES*************/
Route::get('/emprestimo/devolucao/index/','DevolucaoController@index')->name('emprestimo.indexD');
Route::get('/emprestimo/devolucao/itens/','DevolucaoController@devolucao')->name('emprestimo.devolucao');
Route::get('/devolucao/itens/{empCodigo}','DevolucaoController@telaDevolver');
Route::get('/datatable/devolucao/{empCodigo}','DevolucaoController@dataTableJson')->name('devolucao.datatable');
Route::post('/devolucao/storeJson','DevolucaoController@storeJson');
Route::resource('devolver', 'DevolucaoController');

/**************ROTAS DEPRECIAÇÃO*************/
Route::resource('depreciacao', 'DepreciacaoController');


/**************ROTAS TRANSFERÊNCIA*************/
Route::resource('transferencia', 'TransferirController');
Route::get('/transferencia/itens/{patCodigo}', 'TransferirController@getItens');
Route::get('/transferencia/pesquisar/itens/{patCodigo?}', 'TransferirController@pesquisar');

resources/views/autorizacao/create.blade.php
@extends('layouts.master') 
@section('title', '- Autorização')
@section('patrimonioAtivo','bg-danger') 
@section('principal') @parent

<!--Ajax-->
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!--Mascara-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>

<h3 style="margin-left:10px;"><i class="fa fa-book"></i> Autorizações </h3>

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">Autorizações</a></li>
        <li><a href="#tab_2" data-toggle="tab" aria-expanded="true">Cadastro</a></li>
    </ul>
    <div class="tab-content">
        <!--Aba 1-->
        <div class="tab-pane active" id="tab_1">
            <form role="form">
                <div class="">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12" style="margin:15px;padding-bottom:20px;">
                                <div class="table-responsive">
                                    <table class="table table-hover " id="autorizacao-table">
                                        <thead>
                                            <tr>
                                                <th>Nome</th>
                                                <th>Endereço</th>
                                                <th>Numero</th>
                                                <th>Bairro</th>
                                                <th>Cidade</th>
                                                <th>Estado</th>
                                                <th>Opções</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div> 
        <!--Aba 1-->
        <!--Aba 2-->
        <div class="tab-pane " id="tab_2">
            <div class="box-body box-success">
                <form action="{{ route('unidade.store') }}" method="POST">
                    @csrf
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="autNome">Nome <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" id="autNome" name="autNome" placeholder="Digite o nome">
                                    @if($errors->get('autNome'))
                                        @foreach($errors->get('autNome') as $error)
                                            <span class="text-danger">{{ $error }}</span><br>
                                        @endForeach
                                    @endIf
                                </div>
                                <div class="form-group">
                                    <label for="autDescricao">Descrição</label>
                                    <textarea name="autDescricao" id="autDescricao"rows="5" class="form-control"
                                     placeholder="Descreva uma breve relato sobre a autorização"></textarea>
                                    @if($errors->get('autDescricao'))
                                        @foreach($errors->get('autDescricao') as $error)
                                            <span class="text-danger">{{ $error }}</span><br>
                                        @endForeach
                                    @endIf
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="autValor">Valor Permitido <span class="text-danger">*</span></label>
                                    <input type="number" class="form-control" id="autValor" name="autValor">
                                    @if($errors->get('autValor'))
                                        @foreach($errors->get('autValor') as $error)
                                            <span class="text-danger">{{ $error }}</span><br>
                                        @endForeach
                                    @endIf
                                </div>
                                <div class="form-group">
                                    <label for="autData">Data <span class="text-danger">*</span></label>
                                    <input type="date" class="form-control" id="autData" name="autData">
                                    @if($errors->get('autData'))
                                        @foreach($errors->get('autData') as $error)
                                            <span class="text-danger">{{ $error }}</span><br>
                                        @endForeach
                                    @endIf
                                </div>
                                <div class="form-group">
                                    <label for="users_useCodigo">Responsável <span class="text-danger">*</span></label>
                                    <select name="users_useCodigo" id="users_useCodigo" class="form-control">
                                        <option value="0">Selecione</option>
                                        @foreach ($users as $user)
                                            <option value="{{$user->useCodigo}}">{{$user->useNome}}</option>
                                        @endforeach
                                    </select>
                                    @if($errors->get('users_useCodigo'))
                                        @foreach($errors->get('users_useCodigo') as $error)
                                            <span class="text-danger">{{ $error }}</span><br>
                                        @endForeach
                                    @endIf
                                </div>
                                <div class="pull-right">
                                    <div class="form-group">
                                        <a href="{{route('unidade.index')}}" class="btn btn-sm btn-danger">Cancelar</a>
                                        <button type="submit" class="btn btn-sm btn-primary">Cadastrar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>    
                </form>                         
            </div>  
        </div>
        <!--Aba 2-->   
    </div>
</div>

<!--Modal de exclusão-->
@alerta
@endalerta
<!--Modal de exclusão -->  

<script type="text/javascript"> 
    var baseurl = window.location.protocol + '//' + window.location.host + '/';

    //preenchendo o datatable
    jQuery(function() {
            jQuery('#autorizacao-table').DataTable({
                dom: 'lBfrtip',
                "ajax": {
                    "url": '{{ route("autorizacao.datatable") }}',
                    "type": "GET"
                },
                "columns": [{
                        data: 'uniNome',
                        name: 'Nome'
                    },
                    {
                        data: 'endereco.endRua',
                        name: 'Rua'
                    },
                    {
                        data: 'endereco.endNumero',
                        name: 'Numero'
                    },
                    {
                        data: 'endereco.endBairro',
                        name: 'Bairro'
                    },
                    {
                        data: 'endereco.cidade.cidCidade',
                        name: 'Cidade'
                    },
                    {
                        data: 'endereco.estado.estEstado',
                        name: 'Estado'
                    },
                    {
                        data: "uniCodigo",
                        render: function(data, type, row) {
                            var html = '<div class="col-md-6">';
                            html += '<p><a href="unidade/' + data + '/edit" class="btn btn-primary btn-block">';
                            html += '<i class="fa fa-edit"></i>&nbsp; Editar</a></p></div>';
                            html += '<div class="col-md-6">';
                            html += '<p><button type="button" class="btn btn-danger btn-block" onclick="abriModal('+data+')">';
                            html += '<i class="fa fa-remove"></i>&nbsp; Excluir</button></p></div>';
                            return html;
                        },
                        name: 'Opções'
                    }
                ],
                "language": {
                    "url": "http://cdn.datatables.net/plug-ins/1.10.15/i18n/Portuguese-Brasil.json"
                },
                buttons: [
                    'pdfHtml5',
                    'excelHtml5'
                ]
            });
        });

        //preenchendo o modal
        function abriModal(data){
            var uniCodigo = data;
            $.ajax({
				type: 'GET',
				url: baseurl + 'unidade/'+uniCodigo,
                headers: {
						'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				cache: false,
					error: function(response) {
						console.log("Erro:\n"+response);
					},
					success: function(resposta) {
                        if(resposta != 'Vazio'){
                            codigo.value = resposta.unidade.uniCodigo;
                            modalBody.innerHTML = "Tem certeza que deseja excluir a unidade <strong>"+ resposta.unidade.uniNome+"</strong>?";
                            $('#modalExclusao').modal('show');	
                        }else{
                            alert('Não é possível realizar a exclusão,tente mais tarde!');
                        }
					}
            });
        }  
            
        //mandando pro metodo destroy
        function funcaoExcluir(){
            var uniCodigo = codigo.value;
            $.ajax({
                type: 'DELETE',
                url:baseurl+ "unidade/"+uniCodigo,
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
					'Content-Type': 'application/json',
    				'Authorization': '${this.state.tokenType} ${this.state.token}'
				},
                cache: false,
                    error: function(response) {
                        console.log("Erro:\n"+response);
                    },
                    success: function(resposta) {
                        if(resposta == 'true'){
                            $('#modalExclusao').modal('hide');
                            window.location.reload('#tab_2');
                        }else{
                            alert('Não foi possível realizar a exclusão,tente mais tarde!');
                        }
                    }		
                });
            
        }
    </script>

    <script type="text/javascript" src="{{ asset('/data/js/bootstrap-select.js') }}"></script>    
@endsection