routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', function () {
    return view('welcome');
});

Route::get('/teste/pdf',function(){
    return view('teste');
});


Route::get('/home', 'HomeController@index')->name('home');
Route::get('datatable/home','HomeController@dataTableJson')->name('home.datatable');
Route::get('home/categoria','HomeController@getCategorias');
Route::get('home/unidade','HomeController@getUnidades');

/**************ROTAS FUNÇÃO*************/
Route::resource('/funcao', 'FuncaoController');
Route::get('datatable/funcao','FuncaoController@dataTableJson')->name('funcao.datatable');

/**************ROTAS USUÁRIOS*************/
Route::resource('/user', 'UserController');
Route::get('datatable/user','UserController@dataTableJson')->name('user.datatable');
Route::get('/user/perfil/{useCodigo}','UserController@perfil')->name('user.perfil');//visualizar o perfil
Route::post('user/editar','UserController@editarPerfil'); //editar
Route::post('user/uploadFoto','UserController@upload')->name('user.uploadFoto');

/**************ROTAS CATEGORIAS*************/
Route::resource('/categoria', 'CategoriaController');
Route::get('datatable/categoria','CategoriaController@dataTableJson')->name('categoria.datatable');

/**************ROTAS UNIDADES*************/
Route::resource('/unidade', 'UnidadeController');
Route::get('datatable/unidade','UnidadeController@dataTableJson')->name('unidade.datatable');
Route::get('unidade/cidade/{estCodigo}','UnidadeController@getCidades')->name('unidade.cidade');

/**************ROTAS FORNECEDORES*************/
Route::resource('/fornecedor', 'FornecedorController');
Route::get('datatable/fornecedor','FornecedorController@dataTableJson')->name('fornecedor.datatable');
Route::get('fornecedor/verMais/{forCodigo}','FornecedorController@verMais')->name('fornecedor.verMais');
Route::get('fornecedor/cidade/{estCodigo}','FornecedorController@getCidades')->name('fornecedor.cidade');

/**************ROTAS PATRIMONIOS*************/
Route::resource('/patrimonio', 'PatrimonioController');
Route::get('patrimonios/json/{catCodigo?}','PatrimonioController@getPatrimonios');//preencher da tabela
Route::get('patrimonios/pesquisar','PatrimonioController@pesquisa');//pesquisa instantanea
Route::get('patrimonios/export', 'PatrimonioController@export')->name('patrimonio.export');

/**************ROTAS ITENS DE PATRIMONIOS*************/
Route::get('patrimonio/itensPatrimonio/{patCodigo}','PatrimonioController@getItensPatrimonio')->name('patrimonio.itensPatrimonio');
Route::resource('/itensPatrimonio','ItensPatrimonioController');
Route::get('patrimonio/itensPatrimonio/{itpCodigo}/edit','ItensPatrimonioController@edit');//editar um item de patrimonio
Route::get('patrimonio/itensPatrimonio/json/{patCodigo}/{tipoS?}/{valor?}','ItensPatrimonioController@getJson');//preenchendo a tabela
Route::get('filtrarPor/{tipo}','ItensPatrimonioController@preencherFiltro');//preencher o filtro
Route::get('itensPatrimonio/nota_fiscal/{nofCodigo}','ItensPatrimonioController@getNF');//visualizar nota fiscal
Route::get('itensPatrimonios/pesquisar','ItensPatrimonioController@pesquisa');//pesquisa instântanea
Route::get('itensPatrimonio/barcode/{itpCodigo}','ItensPatrimonioController@gerarCodigoBarras');//gerar código de barras
Route::get('itensPatrimonios/pesquisar/notaFiscal','ItensPatrimonioController@pesquisaNF');
Route::get('itens_patrimonio/export/{patCodigo}', 'ItensPatrimonioController@export')->name('itens_patrimonio.export');


/**************ROTAS NOTA FISCAL*************/
Route::resource('/notaFiscal', 'NotaFiscalController');
Route::get('datatable/notaFiscal','NotaFiscalController@dataTableJson')->name('notaFiscal.datatable');
Route::get('visualizar/nota_fiscal/{nofCodifo}','NotaFiscalController@verNF');
Route::post('/notaFiscal/cadastrar','NotaFiscalController@cadastrarJS')->name('notaFiscal.cadastrar');

/**************ROTAS AUTORIZACAO*************/
Route::resource('/autorizacao', 'AutorizacaoController');
Route::get('datatable/autorizacao','AutorizacaoController@dataTableJson')->name('autorizacao.datatable');

/**************ROTAS RELATÓRIOS*************/
Route::resource('relatorios', 'RelatoriosController');

/**************ROTAS EMPRESTIMOS*************/
Route::resource('/emprestimo', 'EmprestimoController');
Route::get('/emprestimo/patrimonios/json/{uniCodigo?}/{status?}/{catCodigo?}/{patCodigo?}','EmprestimoController@getPatrimonios');// listar patrimonios que podem ser emprestados
Route::get('datatable/emprestimo/{empStatus?}/{empData?}','EmprestimoController@dataTableJson')->name('emprestimo.datatable'); // listando os emprestimos
Route::get('/emprestimo/item/adicionar/{itpCodigo}','EmprestimoController@adicionar');// buscando item que foi selecionado para ser emprestado
Route::get('/emprestimo/verMais/{empCodigo}','EmprestimoController@verMais');// ver todos os detalhes do emprestimo
Route::get('/emprestimo/editar/json/{empCodigo}','EmprestimoController@getItensEditar'); // buscar itens que foram emprestados durante o cadastro para edição
Route::get('/emprestimo/editar/item/{itpCodigo}','EmprestimoController@getItem');
Route::get('/emprestimo/listar/pesquisar','EmprestimoController@pesquisarListagem');
Route::get('/emprestimo/adicionar/leitor/{itpCodigoBarras}','EmprestimoController@getItemLeitor'); // buscar item no banco pelo código de barras lido pelo leitor

/**************ROTAS DEVOLUÇÕES*************/
Route::get('/emprestimo/devolucao/index/','DevolucaoController@index')->name('emprestimo.indexD');
Route::get('/emprestimo/devolucao/itens/','DevolucaoController@devolucao')->name('emprestimo.devolucao');
Route::get('/devolucao/itens/{empCodigo}','DevolucaoController@telaDevolver');
Route::get('/datatable/devolucao/{empCodigo}','DevolucaoController@dataTableJson')->name('devolucao.datatable');
Route::post('/devolucao/storeJson','DevolucaoController@storeJson');
Route::resource('devolver', 'DevolucaoController');

/**************ROTAS DEPRECIAÇÃO*************/
Route::resource('depreciacao', 'DepreciacaoController');


/**************ROTAS TRANSFERÊNCIA*************/
Route::resource('transferencia', 'TransferirController');
Route::get('/transferencia/itens/{patCodigo}', 'TransferirController@getItens');
Route::get('/transferencia/pesquisar/itens/{patCodigo?}', 'TransferirController@pesquisar');

app/Categoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    protected $table = "categoria";

    protected $primaryKey = "catCodigo";
    
    protected $fillable = [
        'catNome', 'catDescricao','catVidaUtil', 
    ];

    public function patrimonio(){
        return $this->hasMany('App\Patrimonio','categoria_catCodigo','catCodigo');
    }
}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Categoria;

class CategoriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
	{
        $this->middleware('auth');
        $this->middleware('multiple');
    }
    public function index()
    {
        return view('categoria.create');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $regras =[
            'catNome' =>'required',
            'catVidaUtil'=>'required',
            'catDescricao'=> 'nullable'
        ];
        $mensagens =[
            'catNome.required'=> 'Nome é um requisito obrigatório',
            'catVidaUtil.required'=> 'Vida útil é um requisito obrigatório',
        ];
        $request->validate($regras,$mensagens);
        $categoria = new Categoria();
        $categoria->catNome =$request->catNome;
        $categoria->catDescricao = $request->catDescricao;
        $categoria->catVidaUtil = $request->catVidaUtil;

        $categoria->save();
        return redirect()->route('categoria.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $categoria = Categoria::find($id);
        if($categoria != null){
            return response()->json(['categoria'=>$categoria]);
        }

        return response('Vazio'); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categoria = Categoria::find($id);
        if($categoria == null){
            return redirect()->back();
        }
        return view('categoria.edit',['categoria'=>$categoria]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $categoria = Categoria::find($id);
        if($categoria != null){

            $regras =[
                'catNome' =>'required',
                'catVidaUtil'=>'required',
            ];
            $mensagens =[
                'catNome.required'=> 'Nome é requisito obrigatório',
                'catVidaUtil.required'=> 'Vida útil é requisito obrigatório',
            ];
            $request->validate($regras,$mensagens);

            $categoria->catNome =$request->catNome;
            $categoria->catDescricao = $request->catDescricao;
            $categoria->catVidaUtil = $request->catVidaUtil;
    
            $categoria->update();
            return redirect()->route('categoria.index');
        }

        return redirect()
                ->back()
                ->withSuccess('Não foi possível atualizar o cadastro, tente mais tarde!');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categoria = Categoria::find($id);
        if($categoria != null){
            $categoria->delete();
            return response()->json('true');

        }
        return response()->json('false');
    }

    public function dataTableJson(){
        return response()->json(['data'=>Categoria::all()]);
    }
}

resources/views/categoria/create.blade.php
@extends('layouts.master') @section('title', '- Categoria')@section('cadastrosdiversosAtivo','bg-danger') @section('principal') @parent

<!--Ajax-->
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!--Mascara-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>

<h3 style="margin-left:10px;"><i class="fa fa-bookmark"></i> Categorias </h3>

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li id="li_1" class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">Categorias</a></li>
        <li id="li_2"><a href="#tab_2" data-toggle="tab" aria-expanded="true">Cadastro</a></li>
        
    </ul>
    <div class="tab-content">
        <!--Aba 1-->
        <div class="tab-pane active" id="tab_1">
            <form role="form">
                <div class="">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12" style="margin:15px;padding-bottom:20px;">
                                <div class="table-responsive">
                                    <table class="table table-hover " id="categoria-table">
                                        <thead>
                                            <tr>
                                                <th>Nome</th>
                                                <th>Vida Útil (anos)</th>
                                                <th>Descrição</th>
                                                <th>Opções</th>
                                            </tr>
                                        </thead>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div> 
        <!--Aba 1-->
        <!--Aba 2-->
        <div class="tab-pane " id="tab_2">
            <div class="box-body box-success">
                <form action="{{ route('categoria.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="catNome">Nome <span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" id="catNome" name="catNome" placeholder="Digite o nome da categoria">
                                    @if($errors->get('catNome'))
                                        @foreach($errors->get('catNome') as $error)
                                            <span class="text-danger">{{ $error }}</span><br>
                                        @endForeach
                                    @endIf
                                </div>
                                <div class="form-group">
                                    <label for="catDescricao">Descrição</label>
                                    <textarea  placeholder="Breve descrição sobre a categoria" name="catDescricao" id="catDescricao"rows="5" class="form-control"></textarea>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="catVidaUtil">Vida útil (em anos) <span class="text-danger">*</span></label>
                                    <input type="number" name="catVidaUtil" id="catVidaUtil" class="form-control" placeholder="Vida útil em anos da categoria">
                                    @if($errors->get('catVidaUtil'))
                                        @foreach($errors->get('catVidaUtil') as $error)
                                            <span class="text-danger">{{ $error }}</span><br>
                                        @endForeach
                                    @endIf
                                    <div class="pull-right">
                                        <span class="text-danger">*</span><span>Campos Obrigatórios</span>
                                    </div>
                                    <br>
                                </div>
                                <div class="pull-right">
                                    <div class="form-group">
                                        <a href="{{route('categoria.index')}}" class="btn btn-sm btn-danger">Cancelar</a>
                                        <button type="submit" class="btn btn-sm btn-primary">Cadastrar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>    
                </form>                         
            </div>  
        </div>
        <!--Aba 2-->   
    </div>
</div>
<br>

<!--Modal de exclusão-->
@alerta
@endalerta
<!--Modal de exclusão --> 

<!-- Controle das tabs -->
@if(count($errors)>0)
    <script type="text/javascript">
        $('#tab_1').removeClass('active');
        $('#li_1').removeClass('active');
        $('#tab_2').addClass('active');
        $('#li_2').addClass('active');
    </script>
@else
<script type="text/javascript">
    $('#tab_1').addClass('active');
    $('#li_1').addClass('active');
    $('#tab_2').removeClass('active');
    $('#li_2').removeClass('active');
</script>
@endif
<!-- Controle das tabs -->

<script type="text/javascript"> 
    var baseurl = window.location.protocol + '//' + window.location.host + '/';
    
    jQuery(function() {
            jQuery('#categoria-table').DataTable({ 
                dom: 'lBfrtip',
                "ajax": {
                    "url": '{{ route("categoria.datatable") }}',
                    "type": "GET"
                },
                "columns": [{
                        data: 'catNome',  
                        name: 'Nome'
                    },
                    {
                        data: 'catVidaUtil',
                        name: 'Vida útil'
                    },
                    {
                        data: 'catDescricao',
                        name: 'Descrição'
                    },
                    {
                        data: "catCodigo",
                        render: function(data, type, row) {
                            var html = '<div class="col-md-6">';
                            html += '<p><a href="categoria/' + data + '/edit" class="btn btn-primary btn-block">';
                            html += '<i class="fa fa-edit"></i>&nbsp; Editar</a></p></div>';
                            html += '<div class="col-md-6">';
                            html += '<p><button type="button" class="btn btn-danger btn-block" onclick="abriModal('+data+')">';
                            html += '<i class="fa fa-remove"></i>&nbsp; Excluir</button></p></div>';
                            return html;
                        },
                        name: 'Opções'
                    }
                ],
                "language": {
                    "url": "http://cdn.datatables.net/plug-ins/1.10.15/i18n/Portuguese-Brasil.json"
                },
                buttons: [
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: [0, 1, 2] 
                        }
                    },
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: [0, 1, 2] 
                        }
                    },
                ]
            });
        });

        //preenchendo o modal
        function abriModal(data){
            var catCodigo = data;
            $.ajax({
				type: 'GET',
				url: baseurl + 'categoria/'+catCodigo,
                headers: {
						'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				cache: false,
					error: function(response) {
						console.log("Erro:\n"+response);
					},
					success: function(resposta) {
                        if(resposta != 'Vazio'){
                            codigo.value = resposta.categoria.catCodigo;
                            modalBody.innerHTML = "Tem certeza que deseja excluir a categoria <strong>"+ resposta.categoria.catNome+"</strong>?";
                            $('#modalExclusao').modal('show');	
                        }else{
                            alert('Não é possível realizar a exclusão,tente mais tarde!');
                        }
					}
            });
        }  
            
        //mandando pro metodo destroy
        function funcaoExcluir(){
            var catCodigo = codigo.value;
            $.ajax({
                type: 'DELETE',
                url:baseurl+ "categoria/"+catCodigo,
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
					'Content-Type': 'application/json',
    				'Authorization': '${this.state.tokenType} ${this.state.token}'
				},
                cache: false,
                    error: function(response) {
                        console.log("Erro:\n"+response);
                    },
                    success: function(resposta) {
                        if(resposta == 'true'){
                            $('#modalExclusao').modal('hide');
                            window.location.reload('#tab_2');
                        }else{
                            alert('Não foi possível realizar a exclusão,tente mais tarde!');
                        }
                    }		
                });
            
        }
    </script>

    <script type="text/javascript" src="{{ asset('/data/js/bootstrap-select.js') }}"></script>    
@endsection

resources/views/categoria/edit.blade.php
@extends('layouts.master') @section('title', '- Categoria')@section('cadastrosdiversosAtivo','bg-danger') @section('principal') @parent

<!--Ajax-->
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!--Mascara-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>

<h3 style="margin-left:10px;"><i class="fa fa-edit"></i> Editar Categoria </h3>

<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">Edição</a></li>
        
    </ul>
    <div class="tab-content">
        <!--Aba 1-->
        <div class="tab-pane active" id="tab_1">
            <div class="box-body box-success">
                <form action="{{ route('categoria.update',$categoria->catCodigo) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="catNome">Nome <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" id="catNome" name="catNome" value="{{$categoria->catNome}}">
                                    @if($errors->get('catNome'))
                                        @foreach($errors->get('catNome') as $error)
                                            <span class="text-danger">{{ $error }}</span><br>
                                        @endForeach
                                    @endIf
                                </div>
                                <div class="form-group">
                                    <label for="catDescricao">Descrição</label>
                                    <textarea name="catDescricao" id="catDescricao"rows="5" 
                                    class="form-control">{{$categoria->catDescricao}}</textarea>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="catVidaUtil">Vida útil (em anos) <span class="text-danger">*</span></label>
                                    <input type="number" name="catVidaUtil" id="catVidaUtil" class="form-control" value="{{$categoria->catVidaUtil}}">
                                    @if($errors->get('catVidaUtil'))
                                        @foreach($errors->get('catVidaUtil') as $error)
                                            <span class="text-danger">{{ $error }}</span><br>
                                        @endForeach
                                    @endIf
                                    <div class="pull-right">
                                        <span class="text-danger">*</span><span>Campos Obrigatórios</span>
                                    </div>
                                    <br>
                                </div>
                                <div class="pull-right">
                                    <div class="form-group">
                                        <a href="{{route('categoria.index')}}" class="btn btn-sm btn-danger">Cancelar</a>
                                        <button type="submit" class="btn btn-sm btn-primary">Atualizar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>    
                </form>                         
            </div>  
        </div>
        <!--Aba 1-->   
    </div>
</div>

    <script type="text/javascript" src="{{ asset('/data/js/bootstrap-select.js') }}"></script>    
@endsection